# Generated by Django 5.0.2 on 2025-07-11 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_conversation_options_alter_message_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='chatbot_type',
            field=models.CharField(choices=[('general', 'General Assistant'), ('travel', 'Travel Assistant'), ('learning', 'Learning Assistant'), ('coding', 'Coding Assistant')], default='general', max_length=50),
        ),
    ]
